# Generated by Django 2.1 on 2020-06-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200611_0126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200611_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='content',
            field=models.CharField(blank=True, help_text='200자 이내의 메모를 남길 수 있습니다', max_length=200),
        ),
        migrations.AddField(
            model_name='scrap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='scrap',
            unique_together={('user', 'post')},
        ),
    ]
