# Generated by Django 2.1 on 2020-06-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_like_user_set'),
        ('accounts', '0003_auto_20200611_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_set',
            field=models.ManyToManyField(blank=True, through='accounts.Follow', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='scraping_set',
            field=models.ManyToManyField(blank=True, through='accounts.Scrap', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
