# Generated by Django 2.1 on 2020-06-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200611_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scraping_set',
            new_name='scraped_set',
        ),
    ]
